#!/bin/bash

set -Eeuo pipefail

SCRIPTDIR=$(cd $(dirname $0); pwd)
DATADIR="${SCRIPTDIR}/../data"

export ITF="${DATADIR}/KJJD010I.txt"
export OTF="${DATADIR}/KJBM010O.dat"

"${SCRIPTDIR}/KJBM010/KJBM010" | iconv -f cp932

export ITF="${DATADIR}/KJBM010O.dat"
export OTF="${DATADIR}/KJBM020O.dat"
export COB_LIBRARY_PATH="${SCRIPTDIR}/KCBS010"

"${SCRIPTDIR}/KJBM020/KJBM020" | iconv -f cp932

CTRLFILE=$(mktemp)
trap "rm -f ${CTRLFILE}" EXIT

cat <<_EOF_ > "$CTRLFILE"
SORT FIELDS=(14,5,ZD,A)
USE  ${DATADIR}/KJBM020O.dat RECORD F,100 ORG SQ
GIVE ${DATADIR}/SORT10.dat RECORD F,100 ORG SQ
_EOF_

cat "$CTRLFILE"
gcsort TAKE ${CTRLFILE}

export ITF="${DATADIR}/SORT10.dat"
export IMF="${DATADIR}/KCCFSHO.dat"
export OTF="${DATADIR}/KJBM030O.dat"

"${SCRIPTDIR}/KJBM030/KJBM030" | iconv -f cp932

export ITF="${DATADIR}/KJBM030O.dat"
export OTF1="${DATADIR}/KJBM050O1.dat"
export OTF2="${DATADIR}/KJBM050O2.dat"

"${SCRIPTDIR}/KJBM050/KJBM050" | iconv -f cp932

export ITF="${DATADIR}/KJBM050O1.dat"
export OTF="${DATADIR}/KUBM010O.dat"

"${SCRIPTDIR}/KUBM010/KUBM010" | iconv -f cp932

CTRLFILE=$(mktemp)
trap "rm -f ${CTRLFILE}" EXIT

cat <<_EOF_ > "$CTRLFILE"
SORT FIELDS=(20,5,ZD,A, 2,8,ZD,A)
USE  ${DATADIR}/KUBM010O.dat RECORD F,100 ORG SQ
GIVE ${DATADIR}/SORT20.dat RECORD F,100 ORG SQ
_EOF_

cat "$CTRLFILE"
gcsort TAKE ${CTRLFILE}

export ITF="${DATADIR}/SORT20.dat"
export OTF="${DATADIR}/KUBM020O.dat"

"${SCRIPTDIR}/KUBM020/KUBM020" | iconv -f cp932

